### ISSUE TITLE
Unhandled exception for nonexistent domains

### ISSUE THREAD

**Issue by dspruell-i01** [dspruell/whois-format#5]
In cases where a domain is not present in WHOIS, an unhandled exception is raised:

```
% whois-format hevciak.com
Traceback (most recent call last):
  File "/Users/ds/.local/bin/whois-format", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/ds/.local/pipx/venvs/whois-format/lib/python3.11/site-packages/whois_format.py", line 84, in cli
    w = whois(domain)
        ^^^^^^^^^^^^^
  File "/Users/ds/.local/pipx/venvs/whois-format/lib/python3.11/site-packages/whois/__init__.py", line 52, in whois
    return WhoisEntry.load(domain, text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ds/.local/pipx/venvs/whois-format/lib/python3.11/site-packages/whois/parser.py", line 205, in load
    return WhoisCom(domain, text)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ds/.local/pipx/venvs/whois-format/lib/python3.11/site-packages/whois/parser.py", line 467, in __init__
    raise PywhoisError(text)
whois.parser.PywhoisError: No match for "HEVCIAK.COM".
>>> Last update of whois database: 2023-10-09T19:46:44Z <<<

NOTICE: The expiration date displayed in this record is the date the
registrar's sponsorship of the domain name registration in the registry is
currently set to expire. This date does not necessarily reflect the expiration
date of the domain name registrant's agreement with the sponsoring
registrar.  Users may consult the sponsoring registrar's Whois database to
view the registrar's reported date of expiration for this registration.

TERMS OF USE: You are not authorized to access or query our Whois
database through the use of electronic processes that are high-volume and
automated except as reasonably necessary to register domain names or
modify existing registrations; the Data in VeriSign Global Registry
Services' ("VeriSign") Whois database is provided by VeriSign for
information purposes only, and to assist persons in obtaining information
about or related to a domain name registration record. VeriSign does not
guarantee its accuracy. By submitting a Whois query, you agree to abide
by the following terms of use: You agree that you may use this Data only
for lawful purposes and that under no circumstances will you use this Data
to: (1) allow, enable, or otherwise support the transmission of mass
unsolicited, commercial advertising or solicitations via e-mail, telephone,
or facsimile; or (2) enable high volume, automated, electronic processes
that apply to VeriSign (or its computer systems). The compilation,
repackaging, dissemination or other use of this Data is expressly
prohibited without the prior written consent of VeriSign. You agree not to
use electronic processes that are automated and high-volume to access or
query the Whois database except as reasonably necessary to register
domain names or modify existing registrations. VeriSign reserves the right
to restrict your access to the Whois database in its sole discretion to ensure
operational stability.  VeriSign may restrict or terminate your access to the
Whois database for failure to abide by these terms of use. VeriSign
reserves the right to modify these terms at any time.

The Registry database contains ONLY .COM, .NET, .EDU domains and
Registrars.
```

**Comment by dspruell** [comment]
Fixed with #6.
